//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDashBoard.Model.DASHBOARD.Models
{
    using System;
    using System.Collections.Generic;
    
    public class DASHBOARD_LINE_SHIFT_SETTING
    {
        public int SEQNO { get; set; }
        public string FACTORY_CD { get; set; }
        public string SHIFT_CODE { get; set; }
        public string SHIFT_DESC { get; set; }
        public Nullable<int> SHIFT_SEQ { get; set; }
        public Nullable<System.TimeSpan> SHIFT_FROM { get; set; }
        public Nullable<System.TimeSpan> SHIFT_TO { get; set; }
        public Nullable<decimal> TIME_INTERVAL { get; set; }
        public string ACTIVE { get; set; }
    }
}
