//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDashBoard.Model.DASHBOARD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DASHBOARD_MESSAGE_DEFINITION
    {
        public string FORM_NAME { get; set; }
        public string CONTROLLER_ID { get; set; }
        public string CONTROLLER_TYPE { get; set; }
        public string DESC_EN { get; set; }
        public string DESC_CN { get; set; }
        public string DESC_VN { get; set; }
    }
}
