//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDashBoard.Model.DASHBOARD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DASHBOARD_LINE_RATIO
    {
        public int SEQNO { get; set; }
        public string FACTORY_CD { get; set; }
        public string PRODUCTION_LINE_CD { get; set; }
        public string HRIS_PRODUCTION_LINE_CD { get; set; }
        public Nullable<decimal> RATIO { get; set; }
        public string ACTIVE { get; set; }
    }
}
