//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDashBoard.Model.DASHBOARD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DASHBOARD_PRODUCTION_DATA
    {
        public int SEQNO { get; set; }
        public string FACTORY_CD { get; set; }
        public string PRODUCTION_LINE_CD { get; set; }
        public string GO_NO { get; set; }
        public string GARMENT_TYPE_CD { get; set; }
        public string GO_JO_NO { get; set; }
        public Nullable<int> CUT_QTY { get; set; }
        public Nullable<int> ACTUAL_QTY { get; set; }
        public Nullable<int> GOOD_GARMENT_QTY { get; set; }
        public Nullable<int> REWORKED_GOOD_GARMENT_QTY { get; set; }
        public Nullable<int> WORKMANSHIP_DEFECT_QTY { get; set; }
        public Nullable<int> INSPECT_QTY { get; set; }
        public Nullable<int> NON_WORKMANSHIP_DEFECT_QTY { get; set; }
        public Nullable<decimal> PASS_RATES { get; set; }
        public Nullable<decimal> SAH { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
    }
}
