//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDashBoard.Model.DASHBOARD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DASHBOARD_EMPLOYEE_ATTENDTIME
    {
        [Key]
        public int SEQNO { get; set; }
        public string FACTORY_CD { get; set; }
        public string EMPLOYEE_NO { get; set; }
        public Nullable<System.DateTime> ATTEND_DATE { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string SHIFT { get; set; }
        public Nullable<System.DateTime> TRX_DATE { get; set; }
        public string PRODUCTION_LINE_CD { get; set; }
        public string FACTORY_EMPLOYEE_NO { get; set; }
        public Nullable<System.DateTime> HRIS_CREATE_TIME { get; set; }

    }
}
