//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDashBoard.Model.DASHBOARD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DASHBOARD_QA_PI_HD
    {
        public decimal SEQNO { get; set; }
        public long PI_HD_ID { get; set; }
        public string GO_NO { get; set; }
        public string JO_NO { get; set; }
        public string COLOR_CODE { get; set; }
        public int INSPECT_QTY { get; set; }
        public int GOOD_GARMENT_QTY { get; set; }
        public int WORKMANSHIP_DEFECT_QTY { get; set; }
        public int NON_WORKMANSHIP_DEFECT_QTY { get; set; }
        public string ISLOCK { get; set; }
        public System.DateTime INSPECT_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USERID { get; set; }
        public System.DateTime LAST_MODIFY_DATE { get; set; }
        public string LAST_MODIFY_USERID { get; set; }
        public int CUT_QTY { get; set; }
        public string FACTORY_CD { get; set; }
        public string GARMENT_TYPE_CD { get; set; }
        public string GO_JO_NO { get; set; }
        public int REWORKED_GOOD_GARMENT_QTY { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> VERSION { get; set; }
        public string UPLOAD_MES_FLAG { get; set; }
        public Nullable<System.DateTime> UPLOAD_MES_DATE { get; set; }
        public System.DateTime WORK_FINAL_DATE { get; set; }
        public string TransferFlag { get; set; }
        public string PROCESS_FLAG { get; set; }
        public Nullable<int> INSPECT_QTY_1 { get; set; }
        public Nullable<int> GOOD_GARMENT_QTY_1 { get; set; }
        public Nullable<int> WORKMANSHIP_DEFECT_QTY_1 { get; set; }
        public Nullable<int> NON_WORKMANSHIP_DEFECT_QTY_1 { get; set; }
        public Nullable<int> REWORKED_GOOD_GARMENT_QTY_1 { get; set; }
    }
}
